#! /bin/bash

if which todo; then
    echo "todo is already installed."
    exit 1
fi
echo "Do you care where I install todo?[Y/N]"
read CARE

if [ $CARE = 'Y' ]
then
    echo "Where do you want to install todo?"
    read DEST
    if [ ! -d $DEST ]
    then
        echo "Directory does not exist: $DEST"
        echo "Using default: $HOME/bin"
        DEST="$HOME/bin"
    fi
else
    echo "Using default: $HOME/bin"
    DEST="$HOME/bin"
fi

echo "Installing in: $DEST"

if [ ! -d $DEST ]
then
    mkdir -p $DEST
fi

cp todo kv-bash $DEST

if [[ ":$PATH:" == *":$DEST:"* ]] 
then
    echo "$DEST is on PATH"
else
   echo "Adding $DEST to PATH"
   echo "PATH=\$PATH:$DEST" >> ~/.bashrc
   echo "PATH=\$PATH:$DEST" >> ~/.bash_profile
fi

touch ~/.bashrc && source ~/.bashrc
touch .bash_profile && source ~/.bash_profile

