#! /bin/bash

echo "Do you care where I install todo?[Y/N]"
read CARE

if [ $CARE = 'Y' ]
then
    echo "Where do you want to install todo?"
    read DEST
    echo $DEST
    if [ ! -d $DEST ]
    then
        echo "Directory does not exist: $DEST"
        echo "Using default: $HOME/bin"
        DEST="$HOME/bin"
    fi
else
    echo "Using default: /usr/local/bin"
    DEST="$HOME/bin"
fi

echo "Installing in: $DEST"

if [ ! -d $DEST ]
then
    mkdir -p $DEST
fi

cp todo kv-bash $DEST

if [[ ":$PATH:" == *":$DEST:"* ]] 
then
    echo "$DEST is on PATH"
else
   echo "Adding $DEST to PATH"
   echo "PATH=\$PATH:$DEST" >> ~/.bashrc
   echo "PATH=\$PATH:$DEST" >> ~/.bash_profile
   source ~/.bashrc
   source ~/.bash_profile
fi

echo todo >> ~/.bash_profile
echo todo >> ~/.bashrc
cp todo kv-bash $DEST

